import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";

import "./globals.css";
import "primereact/resources/themes/lara-light-blue/theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider
          value={{
            inputStyle: "filled",
          }}
        >
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
