export const brandon_wi24 = {
  courses: [
    { id: "1", subject: "COGS", code: 1 },
    { id: "2", subject: "ECE", code: 35 },
    { id: "3", subject: "CSE", code: 100 },
    { id: "4", subject: "ECE", code: 109 },
  ],
  lectures: [
    {
      id: "1",
      lecture_letter: "A",
      type: "LE",
      course_id: "1",
      instructor: "Kiyonaga, Anastasia",
      days: "MWF",
      start_time: "14:00",
      end_time: "14:50",
      location: "GH 242",
    },
    {
      id: "2",
      lecture_letter: "A",
      type: "LE",
      course_id: "2",
      instructor: "Schurgers, Curt",
      days: "MWF",
      start_time: "11:00",
      end_time: "11:50",
      location: "CENTR 115",
    },
    {
      id: "3",
      lecture_letter: "A",
      type: "LE",
      course_id: "3",
      instructor: "Moshiri, Niema",
      days: "MWF",
      start_time: "13:00",
      end_time: "13:50",
      location: "CENTR 115",
    },
    {
      id: "4",
      lecture_letter: "A",
      type: "LE",
      course_id: "4",
      instructor: "Poveda Fonseca, Jorge",
      days: "TuTh",
      start_time: "17:00",
      end_time: "18:20",
      location: "FAH 1301",
    },
  ],
  sections: [
    {
      id: "1",
      section_id: "01",
      lecture_id: "1",
      type: "DI",
      days: "M",
      location: "MANDE B-150",
      available_seats: 0,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: "2",
      section_id: "02",
      lecture_id: "1",
      type: "DI",
      days: "M",
      location: "PCYNH 120",
      available_seats: 0,
      start_time: "09:00",
      end_time: "09:50",
      is_required: false,
    },
    {
      id: "3",
      section_id: "03",
      lecture_id: "1",
      type: "DI",
      days: "F",
      location: "PCYNH 120",
      available_seats: 0,
      start_time: "09:00",
      end_time: "09:50",
      is_required: false,
    },
    {
      id: "4",
      section_id: "04",
      lecture_id: "1",
      type: "DI",
      days: "M",
      location: "CSB 005",
      available_seats: 0,
      start_time: "15:00",
      end_time: "15:50",
      is_required: false,
    },
    {
      id: "5",
      section_id: "05",
      lecture_id: "1",
      type: "DI",
      days: "W",
      location: "CSB 005",
      available_seats: 0,
      start_time: "16:00",
      end_time: "16:50",
      is_required: false,
    },
    {
      id: "6",
      section_id: "50",
      lecture_id: "2",
      type: "LA",
      days: "M",
      location: "WLH 2211",
      available_seats: 1,
      start_time: "14:00",
      end_time: "16:50",
      is_required: false,
    },
    {
      id: "7",
      section_id: "51",
      lecture_id: "2",
      type: "LA",
      days: "M",
      location: "WLH 2211",
      available_seats: 0,
      start_time: "17:00",
      end_time: "19:50",
      is_required: false,
    },
    {
      id: "8",
      section_id: "52",
      lecture_id: "2",
      type: "LA",
      days: "Tu",
      location: "WLH 2211",
      available_seats: 0,
      start_time: "08:00",
      end_time: "10:50",
      is_required: false,
    },
    {
      id: "9",
      section_id: "53",
      lecture_id: "2",
      type: "LA",
      days: "Tu",
      location: "WLH 2211",
      available_seats: 1,
      start_time: "14:00",
      end_time: "16:50",
      is_required: false,
    },
    {
      id: "10",
      section_id: "54",
      lecture_id: "2",
      type: "LA",
      days: "Tu",
      location: "WLH 2211",
      available_seats: 1,
      start_time: "17:00",
      end_time: "19:50",
      is_required: false,
    },
    {
      id: "11",
      section_id: "55",
      lecture_id: "2",
      type: "LA",
      days: "W",
      location: "WLH 2211",
      available_seats: 1,
      start_time: "14:00",
      end_time: "16:50",
      is_required: false,
    },
    {
      id: "12",
      section_id: "01",
      lecture_id: "2",
      type: "DI",
      days: "F",
      location: "CENTR 216",
      available_seats: 0,
      start_time: "13:00",
      end_time: "13:50",
      is_required: true,
    },
    {
      id: "13",
      section_id: "02",
      lecture_id: "2",
      type: "DI",
      days: "W",
      location: "CENTR 214",
      available_seats: 0,
      start_time: "09:00",
      end_time: "09:50",
      is_required: true,
    },
    {
      id: "14",
      section_id: "01",
      lecture_id: "3",
      type: "DI",
      days: "W",
      location: "WLH 2005",
      available_seats: 0,
      start_time: "18:00",
      end_time: "18:50",
      is_required: false,
    },
    {
      id: "15",
      section_id: "01",
      lecture_id: "4",
      type: "DI",
      days: "F",
      location: "MOS 0114",
      available_seats: 57,
      start_time: "12:00",
      end_time: "12:50",
      is_required: false,
    },
  ],
};
