export const dummyCourses = {
  courses: [
    {
      id: 1,
      subject: "CSE",
      code: 186,
    },
    {
      id: 2,
      subject: "CSE",
      code: 274,
    },
    {
      id: 3,
      subject: "CSE",
      code: 361,
    },
    {
      id: 4,
      subject: "CSE",
      code: 140,
    },
    {
      id: 5,
      subject: "CSE",
      code: 266,
    },
    {
      id: 6,
      subject: "CSE",
      code: 251,
    },
    {
      id: 7,
      subject: "CSE",
      code: 443,
    },
    {
      id: 8,
      subject: "CSE",
      code: 376,
    },
    {
      id: 9,
      subject: "CSE",
      code: 312,
    },
    {
      id: 10,
      subject: "CSE",
      code: 400,
    },
    {
      id: 11,
      subject: "CSE",
      code: 203,
    },
    {
      id: 12,
      subject: "CSE",
      code: 469,
    },
    {
      id: 13,
      subject: "CSE",
      code: 150,
    },
    {
      id: 14,
      subject: "CSE",
      code: 480,
    },
    {
      id: 15,
      subject: "CSE",
      code: 331,
    },
    {
      id: 16,
      subject: "CSE",
      code: 306,
    },
    {
      id: 17,
      subject: "CSE",
      code: 279,
    },
    {
      id: 18,
      subject: "CSE",
      code: 287,
    },
    {
      id: 19,
      subject: "CSE",
      code: 488,
    },
    {
      id: 20,
      subject: "CSE",
      code: 109,
    },
  ],
  lectures: [
    {
      id: 1,
      lecture_letter: "D",
      course_id: 1,
      instructor: "Prof. Smith",
      days: ["M", "W", "F"],
      start_time: "13:00",
      end_time: "13:50",
      location: "Building 1 Room 147",
    },
    {
      id: 2,
      lecture_letter: "A",
      course_id: 1,
      instructor: "Prof. Smith",
      days: ["M", "W", "F"],
      start_time: "16:00",
      end_time: "16:50",
      location: "Building 1 Room 264",
    },
    {
      id: 3,
      lecture_letter: "D",
      course_id: 2,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "15:30",
      end_time: "16:50",
      location: "Building 13 Room 100",
    },
    {
      id: 4,
      lecture_letter: "B",
      course_id: 2,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "15:30",
      end_time: "16:50",
      location: "Building 5 Room 482",
    },
    {
      id: 5,
      lecture_letter: "C",
      course_id: 2,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "11:00",
      end_time: "12:20",
      location: "Building 4 Room 128",
    },
    {
      id: 6,
      lecture_letter: "A",
      course_id: 3,
      instructor: "Prof. Johnson",
      days: ["M", "W", "F"],
      start_time: "11:00",
      end_time: "11:50",
      location: "Building 1 Room 373",
    },
    {
      id: 7,
      lecture_letter: "D",
      course_id: 4,
      instructor: "Prof. Johnson",
      days: ["Tu", "Th"],
      start_time: "12:30",
      end_time: "13:50",
      location: "Building 13 Room 266",
    },
    {
      id: 8,
      lecture_letter: "C",
      course_id: 4,
      instructor: "Prof. Garcia",
      days: ["M", "W", "F"],
      start_time: "09:00",
      end_time: "09:50",
      location: "Building 6 Room 397",
    },
    {
      id: 9,
      lecture_letter: "A",
      course_id: 4,
      instructor: "Prof. Brown",
      days: ["Tu", "Th"],
      start_time: "14:00",
      end_time: "15:20",
      location: "Building 13 Room 234",
    },
    {
      id: 10,
      lecture_letter: "C",
      course_id: 5,
      instructor: "Prof. Johnson",
      days: ["Tu", "Th"],
      start_time: "15:30",
      end_time: "16:50",
      location: "Building 7 Room 229",
    },
    {
      id: 11,
      lecture_letter: "D",
      course_id: 5,
      instructor: "Prof. Johnson",
      days: ["M", "W", "F"],
      start_time: "12:00",
      end_time: "12:50",
      location: "Building 14 Room 202",
    },
    {
      id: 12,
      lecture_letter: "D",
      course_id: 6,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "11:00",
      end_time: "12:20",
      location: "Building 2 Room 246",
    },
    {
      id: 13,
      lecture_letter: "A",
      course_id: 7,
      instructor: "Prof. Garcia",
      days: ["Tu", "Th"],
      start_time: "09:30",
      end_time: "10:50",
      location: "Building 12 Room 404",
    },
    {
      id: 14,
      lecture_letter: "C",
      course_id: 7,
      instructor: "Prof. Brown",
      days: ["Tu", "Th"],
      start_time: "14:00",
      end_time: "15:20",
      location: "Building 9 Room 481",
    },
    {
      id: 15,
      lecture_letter: "B",
      course_id: 8,
      instructor: "Prof. Davis",
      days: ["M", "W", "F"],
      start_time: "10:00",
      end_time: "10:50",
      location: "Building 15 Room 477",
    },
    {
      id: 16,
      lecture_letter: "A",
      course_id: 8,
      instructor: "Prof. Lee",
      days: ["M", "W", "F"],
      start_time: "09:00",
      end_time: "09:50",
      location: "Building 10 Room 296",
    },
    {
      id: 17,
      lecture_letter: "D",
      course_id: 8,
      instructor: "Prof. Smith",
      days: ["Tu", "Th"],
      start_time: "12:30",
      end_time: "13:50",
      location: "Building 9 Room 334",
    },
    {
      id: 18,
      lecture_letter: "C",
      course_id: 9,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "08:00",
      end_time: "09:20",
      location: "Building 2 Room 239",
    },
    {
      id: 19,
      lecture_letter: "C",
      course_id: 10,
      instructor: "Prof. Johnson",
      days: ["Tu", "Th"],
      start_time: "11:00",
      end_time: "12:20",
      location: "Building 11 Room 121",
    },
    {
      id: 20,
      lecture_letter: "D",
      course_id: 10,
      instructor: "Prof. Smith",
      days: ["Tu", "Th"],
      start_time: "08:00",
      end_time: "09:20",
      location: "Building 8 Room 111",
    },
    {
      id: 21,
      lecture_letter: "B",
      course_id: 10,
      instructor: "Prof. Johnson",
      days: ["M", "W", "F"],
      start_time: "16:00",
      end_time: "16:50",
      location: "Building 3 Room 401",
    },
    {
      id: 22,
      lecture_letter: "D",
      course_id: 11,
      instructor: "Prof. Brown",
      days: ["Tu", "Th"],
      start_time: "08:00",
      end_time: "09:20",
      location: "Building 14 Room 323",
    },
    {
      id: 23,
      lecture_letter: "A",
      course_id: 11,
      instructor: "Prof. Garcia",
      days: ["M", "W", "F"],
      start_time: "10:00",
      end_time: "10:50",
      location: "Building 13 Room 468",
    },
    {
      id: 24,
      lecture_letter: "A",
      course_id: 12,
      instructor: "Prof. Smith",
      days: ["M", "W", "F"],
      start_time: "13:00",
      end_time: "13:50",
      location: "Building 7 Room 317",
    },
    {
      id: 25,
      lecture_letter: "C",
      course_id: 13,
      instructor: "Prof. Martinez",
      days: ["M", "W", "F"],
      start_time: "14:00",
      end_time: "14:50",
      location: "Building 14 Room 138",
    },
    {
      id: 26,
      lecture_letter: "B",
      course_id: 13,
      instructor: "Prof. Lee",
      days: ["M", "W", "F"],
      start_time: "14:00",
      end_time: "14:50",
      location: "Building 13 Room 345",
    },
    {
      id: 27,
      lecture_letter: "A",
      course_id: 13,
      instructor: "Prof. Johnson",
      days: ["Tu", "Th"],
      start_time: "14:00",
      end_time: "15:20",
      location: "Building 3 Room 106",
    },
    {
      id: 28,
      lecture_letter: "C",
      course_id: 14,
      instructor: "Prof. Lee",
      days: ["M", "W", "F"],
      start_time: "15:00",
      end_time: "15:50",
      location: "Building 5 Room 312",
    },
    {
      id: 29,
      lecture_letter: "C",
      course_id: 15,
      instructor: "Prof. Lee",
      days: ["Tu", "Th"],
      start_time: "14:00",
      end_time: "15:20",
      location: "Building 13 Room 128",
    },
    {
      id: 30,
      lecture_letter: "A",
      course_id: 15,
      instructor: "Prof. Smith",
      days: ["M", "W", "F"],
      start_time: "11:00",
      end_time: "11:50",
      location: "Building 11 Room 396",
    },
    {
      id: 31,
      lecture_letter: "D",
      course_id: 15,
      instructor: "Prof. Garcia",
      days: ["M", "W", "F"],
      start_time: "16:00",
      end_time: "16:50",
      location: "Building 9 Room 124",
    },
    {
      id: 32,
      lecture_letter: "D",
      course_id: 16,
      instructor: "Prof. Johnson",
      days: ["M", "W", "F"],
      start_time: "08:00",
      end_time: "08:50",
      location: "Building 15 Room 353",
    },
    {
      id: 33,
      lecture_letter: "B",
      course_id: 17,
      instructor: "Prof. Brown",
      days: ["Tu", "Th"],
      start_time: "15:30",
      end_time: "16:50",
      location: "Building 6 Room 268",
    },
    {
      id: 34,
      lecture_letter: "B",
      course_id: 18,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "12:30",
      end_time: "13:50",
      location: "Building 1 Room 121",
    },
    {
      id: 35,
      lecture_letter: "C",
      course_id: 18,
      instructor: "Prof. Martinez",
      days: ["M", "W", "F"],
      start_time: "12:00",
      end_time: "12:50",
      location: "Building 2 Room 482",
    },
    {
      id: 36,
      lecture_letter: "D",
      course_id: 18,
      instructor: "Prof. Davis",
      days: ["M", "W", "F"],
      start_time: "14:00",
      end_time: "14:50",
      location: "Building 15 Room 115",
    },
    {
      id: 37,
      lecture_letter: "C",
      course_id: 19,
      instructor: "Prof. Lee",
      days: ["M", "W", "F"],
      start_time: "13:00",
      end_time: "13:50",
      location: "Building 2 Room 152",
    },
    {
      id: 38,
      lecture_letter: "C",
      course_id: 20,
      instructor: "Prof. Davis",
      days: ["M", "W", "F"],
      start_time: "12:00",
      end_time: "12:50",
      location: "Building 12 Room 354",
    },
    {
      id: 39,
      lecture_letter: "D",
      course_id: 20,
      instructor: "Prof. Davis",
      days: ["Tu", "Th"],
      start_time: "09:30",
      end_time: "10:50",
      location: "Building 4 Room 378",
    },
  ],
  sections: [
    {
      id: 1,
      section_id: "051",
      lecture_id: 1,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 7 Room 103",
      available_seats: 39,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 2,
      section_id: "052",
      lecture_id: 1,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 10 Room 209",
      available_seats: 45,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 3,
      section_id: "053",
      lecture_id: 1,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 15 Room 498",
      available_seats: 38,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 4,
      section_id: "001",
      lecture_id: 1,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 14 Room 418",
      available_seats: 43,
      start_time: "17:00",
      end_time: "17:50",
      is_required: true,
    },
    {
      id: 5,
      section_id: "051",
      lecture_id: 2,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 8 Room 434",
      available_seats: 42,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 6,
      section_id: "052",
      lecture_id: 2,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 15 Room 340",
      available_seats: 31,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 7,
      section_id: "053",
      lecture_id: 2,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 14 Room 332",
      available_seats: 22,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 8,
      section_id: "001",
      lecture_id: 3,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 6 Room 406",
      available_seats: 29,
      start_time: "15:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 9,
      section_id: "051",
      lecture_id: 3,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 12 Room 160",
      available_seats: 34,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 10,
      section_id: "052",
      lecture_id: 3,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 5 Room 412",
      available_seats: 29,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: 11,
      section_id: "053",
      lecture_id: 3,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 6 Room 190",
      available_seats: 31,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 12,
      section_id: "001",
      lecture_id: 4,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 10 Room 184",
      available_seats: 44,
      start_time: "08:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 13,
      section_id: "051",
      lecture_id: 5,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 14 Room 205",
      available_seats: 16,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 14,
      section_id: "052",
      lecture_id: 5,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 1 Room 398",
      available_seats: 49,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 15,
      section_id: "053",
      lecture_id: 5,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 11 Room 145",
      available_seats: 27,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 16,
      section_id: "001",
      lecture_id: 6,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 6 Room 184",
      available_seats: 34,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 17,
      section_id: "051",
      lecture_id: 7,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 10 Room 439",
      available_seats: 43,
      start_time: "15:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 18,
      section_id: "001",
      lecture_id: 7,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 1 Room 329",
      available_seats: 23,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 19,
      section_id: "051",
      lecture_id: 8,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 5 Room 191",
      available_seats: 31,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 20,
      section_id: "001",
      lecture_id: 8,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 11 Room 462",
      available_seats: 47,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 21,
      section_id: "002",
      lecture_id: 8,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 6 Room 489",
      available_seats: 12,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 22,
      section_id: "003",
      lecture_id: 8,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 13 Room 133",
      available_seats: 38,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: 23,
      section_id: "001",
      lecture_id: 9,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 10 Room 231",
      available_seats: 24,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 24,
      section_id: "051",
      lecture_id: 9,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 5 Room 279",
      available_seats: 43,
      start_time: "11:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 25,
      section_id: "001",
      lecture_id: 10,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 8 Room 315",
      available_seats: 37,
      start_time: "11:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 26,
      section_id: "051",
      lecture_id: 11,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 6 Room 206",
      available_seats: 11,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 27,
      section_id: "052",
      lecture_id: 11,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 8 Room 490",
      available_seats: 27,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 28,
      section_id: "053",
      lecture_id: 11,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 2 Room 393",
      available_seats: 50,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 29,
      section_id: "051",
      lecture_id: 12,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 10 Room 202",
      available_seats: 27,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 30,
      section_id: "001",
      lecture_id: 13,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 6 Room 222",
      available_seats: 35,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 31,
      section_id: "051",
      lecture_id: 14,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 11 Room 305",
      available_seats: 12,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 32,
      section_id: "001",
      lecture_id: 14,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 6 Room 268",
      available_seats: 30,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 33,
      section_id: "051",
      lecture_id: 15,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 9 Room 309",
      available_seats: 31,
      start_time: "08:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 34,
      section_id: "051",
      lecture_id: 16,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 1 Room 217",
      available_seats: 15,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 35,
      section_id: "001",
      lecture_id: 17,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 11 Room 218",
      available_seats: 12,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 36,
      section_id: "002",
      lecture_id: 17,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 5 Room 173",
      available_seats: 34,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 37,
      section_id: "051",
      lecture_id: 17,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 2 Room 147",
      available_seats: 17,
      start_time: "08:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 38,
      section_id: "051",
      lecture_id: 18,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 8 Room 499",
      available_seats: 33,
      start_time: "08:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 39,
      section_id: "001",
      lecture_id: 18,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 9 Room 256",
      available_seats: 30,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 40,
      section_id: "002",
      lecture_id: 18,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 15 Room 466",
      available_seats: 35,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 41,
      section_id: "003",
      lecture_id: 18,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 11 Room 241",
      available_seats: 50,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 42,
      section_id: "001",
      lecture_id: 19,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 8 Room 253",
      available_seats: 21,
      start_time: "09:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 43,
      section_id: "051",
      lecture_id: 20,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 5 Room 334",
      available_seats: 43,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 44,
      section_id: "052",
      lecture_id: 20,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 5 Room 192",
      available_seats: 15,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 45,
      section_id: "001",
      lecture_id: 21,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 10 Room 382",
      available_seats: 10,
      start_time: "09:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 46,
      section_id: "051",
      lecture_id: 21,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 15 Room 453",
      available_seats: 45,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 47,
      section_id: "001",
      lecture_id: 22,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 15 Room 458",
      available_seats: 50,
      start_time: "11:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 48,
      section_id: "051",
      lecture_id: 22,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 10 Room 394",
      available_seats: 34,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 49,
      section_id: "052",
      lecture_id: 22,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 6 Room 276",
      available_seats: 30,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 50,
      section_id: "053",
      lecture_id: 22,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 1 Room 153",
      available_seats: 34,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 51,
      section_id: "051",
      lecture_id: 23,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 8 Room 246",
      available_seats: 18,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 52,
      section_id: "052",
      lecture_id: 23,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 14 Room 318",
      available_seats: 40,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 53,
      section_id: "051",
      lecture_id: 24,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 11 Room 145",
      available_seats: 32,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 54,
      section_id: "052",
      lecture_id: 24,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 9 Room 415",
      available_seats: 41,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 55,
      section_id: "053",
      lecture_id: 24,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 2 Room 144",
      available_seats: 39,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 56,
      section_id: "001",
      lecture_id: 24,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 14 Room 347",
      available_seats: 31,
      start_time: "09:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 57,
      section_id: "051",
      lecture_id: 25,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 10 Room 239",
      available_seats: 38,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 58,
      section_id: "052",
      lecture_id: 25,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 4 Room 371",
      available_seats: 43,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 59,
      section_id: "053",
      lecture_id: 25,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 8 Room 213",
      available_seats: 50,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 60,
      section_id: "001",
      lecture_id: 25,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 8 Room 461",
      available_seats: 39,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 61,
      section_id: "001",
      lecture_id: 26,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 2 Room 375",
      available_seats: 10,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 62,
      section_id: "051",
      lecture_id: 26,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 8 Room 191",
      available_seats: 19,
      start_time: "08:00",
      end_time: "08:50",
      is_required: false,
    },
    {
      id: 63,
      section_id: "052",
      lecture_id: 26,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 2 Room 471",
      available_seats: 10,
      start_time: "14:00",
      end_time: "14:50",
      is_required: false,
    },
    {
      id: 64,
      section_id: "051",
      lecture_id: 27,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 12 Room 166",
      available_seats: 41,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 65,
      section_id: "001",
      lecture_id: 27,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 4 Room 144",
      available_seats: 35,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 66,
      section_id: "051",
      lecture_id: 28,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 4 Room 252",
      available_seats: 15,
      start_time: "09:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 67,
      section_id: "001",
      lecture_id: 28,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 13 Room 119",
      available_seats: 48,
      start_time: "15:30",
      end_time: "16:20",
      is_required: false,
    },
    {
      id: 68,
      section_id: "001",
      lecture_id: 29,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 13 Room 461",
      available_seats: 17,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 69,
      section_id: "051",
      lecture_id: 29,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 14 Room 356",
      available_seats: 45,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 70,
      section_id: "052",
      lecture_id: 29,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 1 Room 216",
      available_seats: 13,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 71,
      section_id: "001",
      lecture_id: 30,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 13 Room 271",
      available_seats: 25,
      start_time: "11:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 72,
      section_id: "001",
      lecture_id: 31,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 9 Room 289",
      available_seats: 36,
      start_time: "08:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 73,
      section_id: "051",
      lecture_id: 31,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 8 Room 480",
      available_seats: 21,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: 74,
      section_id: "051",
      lecture_id: 32,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 8 Room 208",
      available_seats: 16,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 75,
      section_id: "051",
      lecture_id: 33,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 14 Room 166",
      available_seats: 27,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 76,
      section_id: "001",
      lecture_id: 33,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 9 Room 128",
      available_seats: 27,
      start_time: "11:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 77,
      section_id: "051",
      lecture_id: 34,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 10 Room 398",
      available_seats: 39,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 78,
      section_id: "001",
      lecture_id: 34,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 12 Room 445",
      available_seats: 49,
      start_time: "09:30",
      end_time: "10:20",
      is_required: false,
    },
    {
      id: 79,
      section_id: "001",
      lecture_id: 35,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 14 Room 197",
      available_seats: 43,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: 80,
      section_id: "051",
      lecture_id: 35,
      meeting_type: "LA",
      days: ["M", "W"],
      location: "Building 11 Room 472",
      available_seats: 22,
      start_time: "12:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 81,
      section_id: "051",
      lecture_id: 36,
      meeting_type: "LA",
      days: ["T", "Th"],
      location: "Building 8 Room 262",
      available_seats: 49,
      start_time: "15:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 82,
      section_id: "001",
      lecture_id: 36,
      meeting_type: "DI",
      days: ["M", "W"],
      location: "Building 6 Room 206",
      available_seats: 11,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
    {
      id: 83,
      section_id: "002",
      lecture_id: 36,
      meeting_type: "DI",
      days: ["W", "F"],
      location: "Building 15 Room 362",
      available_seats: 24,
      start_time: "12:30",
      end_time: "13:20",
      is_required: false,
    },
    {
      id: 84,
      section_id: "051",
      lecture_id: 37,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 15 Room 396",
      available_seats: 47,
      start_time: "14:00",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 85,
      section_id: "051",
      lecture_id: 38,
      meeting_type: "LA",
      days: ["W", "F"],
      location: "Building 15 Room 124",
      available_seats: 39,
      start_time: "15:30",
      end_time: "08:50",
      is_required: true,
    },
    {
      id: 86,
      section_id: "001",
      lecture_id: 39,
      meeting_type: "DI",
      days: ["T", "Th"],
      location: "Building 12 Room 369",
      available_seats: 39,
      start_time: "11:00",
      end_time: "11:50",
      is_required: false,
    },
  ],
};
